title: "Introduction to Artificial Intelligence"
description: "This is the course website for CS580: Introduction to Artificial Intelligence"
baseurl: "/cs580"
url: "https://radioheado.github.io"
repository: radioheado/cs580
theme: "just-the-docs"
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-archives
  - jemoji
  - jekyll-gist
  - jekyll-assets
  - jekyll-redirect-from